'use client';

import Image from 'next/image';
import { useEffect, useState } from 'react';
import { BookmarkCheck, CalendarDays, CheckCircle2, ChevronDown, ChevronUp, CircleAlert, Clock3, Mail, MessageSquareQuote, Phone, Printer, Quote, Share2, ShieldCheck, Stethoscope, UserRound } from 'lucide-react';
import type { TipTapDocument } from '@/types/blog';
import { ArticleContent, type TemplatePreviewProps } from './template-one-preview';
import { addTableOfContentsIds, buildTableOfContents, TableOfContents, type TableOfContentsItem } from './table-of-contents';

const ids = { takeaways: 'key-takeaways', intro: 'article-introduction', comparison: 'visual-comparison', numbered: 'numbered-list', expert: 'doctor-insight', guidance: 'medical-guidance', faq: 'frequently-asked-questions' } as const;
const indexItem = (id: string, text: string): TableOfContentsItem => ({ id, text, level: 2 });
function Heading({ children }: { children: React.ReactNode }) { return <h2 className="text-xl font-black tracking-tight text-[#0875c9] sm:text-2xl">{children}</h2>; }
function Meta({ icon: Icon, children }: { icon: typeof Clock3; children: React.ReactNode }) { return <span className="inline-flex items-center gap-2 text-xs font-semibold text-blue-50"><Icon size={14} aria-hidden="true" />{children}</span>; }

export function TemplateTwoPreview({ content, ...props }: TemplatePreviewProps & { content?: TipTapDocument | null }) {
  const [openFaq, setOpenFaq] = useState(0);
  const [active, setActive] = useState('');
  const b = props.blocks?.blocks;
  const breadcrumb = b?.hero.breadcrumb.filter((value) => value.trim()) ?? [];
  const reviewer = b ? [b.hero.reviewer.name, b.hero.reviewer.credentials].filter((value) => value.trim()).join(', ') : '';
  const takeaways = b?.key_takeaways.enabled ? b.key_takeaways.items.filter((value) => value.trim()) : [];
  const comparisons = b?.image_comparison.enabled ? b.image_comparison.items.filter((item) => item.title.trim() || item.description.trim()).map((item) => ({ ...item, image: item.media_id ? props.blockMedia?.[item.media_id]?.original_url ?? null : null, alt: item.media_id ? props.blockMedia?.[item.media_id]?.alt_text ?? null : null })) : [];
  const numbered = b?.numbered_list.enabled ? b.numbered_list.items.filter((item) => item.title.trim() || item.description.trim()) : [];
  const expert = b?.expert_quote.enabled && b.expert_quote.quote.trim() ? { ...b.expert_quote, image: b.expert_quote.media_id ? props.blockMedia?.[b.expert_quote.media_id]?.original_url ?? null : null, alt: b.expert_quote.media_id ? props.blockMedia?.[b.expert_quote.media_id]?.alt_text ?? null : null } : null;
  const cta = b?.medical_cta.enabled && (b.medical_cta.heading.trim() || b.medical_cta.description.trim()) ? b.medical_cta : null;
  const faqs = b?.faq.enabled ? b.faq.items.filter((item) => item.question.trim() || item.answer.trim()) : [];
  const richItems = buildTableOfContents(content);
  const html = addTableOfContentsIds(props.html, richItems);
  const toc = (() => {
    const result: TableOfContentsItem[] = [];
    if (takeaways.length) result.push(indexItem(ids.takeaways, b?.key_takeaways.heading || 'Key Takeaways'));
    if (props.html.trim()) { result.push(indexItem(ids.intro, 'Article Introduction')); result.push(...richItems.map((item) => ({ ...item, level: Math.min(4, item.level + 1) as 3 | 4 }))); }
    if (comparisons.length) result.push(indexItem(ids.comparison, b?.image_comparison.heading || 'Comparison'));
    if (numbered.length) result.push(indexItem(ids.numbered, b?.numbered_list.heading || 'Symptoms'));
    if (expert) result.push(indexItem(ids.expert, 'Doctor’s Insight'));
    if (cta) result.push(indexItem(ids.guidance, 'Medical Guidance'));
    if (faqs.length) result.push(indexItem(ids.faq, b?.faq.heading || 'FAQs'));
    return result;
  })();
  const tocIds = toc.map((item) => item.id).join('|');

  useEffect(() => {
    if (typeof IntersectionObserver === 'undefined') return;
    const elements = tocIds.split('|').filter(Boolean).map((id) => document.getElementById(id)).filter((item): item is HTMLElement => Boolean(item));
    const observer = new IntersectionObserver((entries) => { const hit = entries.filter((entry) => entry.isIntersecting).sort((a, z) => a.boundingClientRect.top - z.boundingClientRect.top)[0]; if (hit) setActive(hit.target.id); }, { rootMargin: '-18% 0px -68% 0px', threshold: [0, 0.15] });
    elements.forEach((element) => observer.observe(element));
    return () => observer.disconnect();
  }, [tocIds]);

  const primary = cta?.primary.label.trim() ? cta.primary : null;
  const secondary = cta?.secondary.label.trim() ? cta.secondary : null;
  return <article data-template="template_2" data-template-version="1" className="mx-auto w-full max-w-[1180px] overflow-x-hidden bg-white pb-12">
    <section data-region="hero" className="relative min-h-[360px] overflow-hidden rounded-[26px] bg-[#0875c9] sm:min-h-[430px] lg:min-h-[500px]">
      {props.image ? <Image src={props.image} alt={props.imageAlt ?? ''} fill priority sizes="(min-width:1280px) 1180px,100vw" className="object-cover" unoptimized /> : props.showFeaturedImagePlaceholder ? <div role="img" aria-label="Sample featured image placeholder" className="absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,#bae6fd_0,#7dd3fc_24%,#0c4a6e_72%)]" /> : null}
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,112,210,.9)_0%,rgba(12,126,218,.82)_55%,rgba(26,137,218,.7)_100%)]" />
      <div className="relative z-10 flex min-h-[360px] max-w-3xl flex-col justify-center px-5 py-10 sm:min-h-[430px] sm:px-10 lg:min-h-[500px] lg:px-14">
        {breadcrumb.length ? <nav aria-label="Breadcrumb" className="mb-4 flex flex-wrap gap-2 text-xs font-semibold text-blue-100">{breadcrumb.map((item, index) => <span key={`${item}-${index}`} className="inline-flex gap-2"><span>{item}</span>{index < breadcrumb.length - 1 ? <span aria-hidden="true">/</span> : null}</span>)}</nav> : null}
        {b?.hero.category.trim() ? <span className="w-fit rounded-full border border-white/35 bg-white/15 px-3 py-1.5 text-[11px] font-black uppercase tracking-[.17em] text-white">{b.hero.category}</span> : null}
        <h1 data-region="article-title" className="mt-4 max-w-2xl text-[28px] font-black leading-[1.12] tracking-tight text-white sm:text-4xl lg:text-[40px]">{props.title || 'Untitled Blog'}</h1>
        {props.excerpt ? <p data-region="excerpt" className="mt-4 max-w-2xl text-sm leading-6 text-blue-50 sm:text-base">{props.excerpt}</p> : null}
        {props.author || reviewer || b?.hero.reading_time_minutes ? <div data-region="metadata" className="mt-6 flex flex-wrap gap-x-5 gap-y-3 border-t border-white/25 pt-4">{props.author ? <Meta icon={UserRound}>{props.author}</Meta> : null}{reviewer ? <Meta icon={Stethoscope}>{reviewer}</Meta> : null}{b?.hero.reading_time_minutes ? <Meta icon={Clock3}>{b.hero.reading_time_minutes} min read</Meta> : null}</div> : null}
      </div>
    </section>
    <div data-region="article-with-sidebar" className="mx-auto grid max-w-[1120px] gap-6 px-4 pt-8 sm:px-7 lg:grid-cols-[minmax(0,1fr)_300px] lg:px-8"><main className="min-w-0">
      {takeaways.length ? <section id={ids.takeaways} data-region="key-takeaways" className="scroll-mt-28 rounded-[18px] border-l-[3px] border-[#1686d9] bg-[#eef8ff] p-5 sm:p-6"><div className="flex items-center gap-2 text-[#0875c9]"><BookmarkCheck size={18} aria-hidden="true" /><h2 className="text-sm font-black uppercase tracking-[.12em]">{b?.key_takeaways.heading || 'Key Takeaways'}</h2></div><ul className="mt-4 space-y-2">{takeaways.map((item, index) => <li key={`${item}-${index}`} className="flex items-start gap-3 text-sm font-semibold leading-6 text-slate-700"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[#1686d9]" aria-hidden="true" /><span>{item}</span></li>)}</ul></section> : null}
      {props.html.trim() ? <section id={ids.intro} data-region="article-content" className="scroll-mt-28 pt-10"><ArticleContent html={html} withRegion={false} /></section> : null}
      {comparisons.length ? <section id={ids.comparison} data-region="visual-comparison" className="scroll-mt-28 pt-11"><Heading>{b?.image_comparison.heading || 'Visual comparison'}</Heading><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{comparisons.map((card, index) => <article key={`${card.title}-${index}`} className="flex min-h-full flex-col overflow-hidden rounded-2xl border border-blue-100 bg-[#eef8ff]"><div className="relative aspect-[4/3] border-t-2 border-[#1686d9] bg-gradient-to-br from-blue-100 to-slate-100">{card.image ? <Image src={card.image} alt={card.alt || card.title} fill loading="lazy" sizes="(min-width:1280px) 230px,(min-width:640px) 50vw,100vw" className="object-cover" unoptimized /> : <div className="grid h-full place-items-center text-xs font-bold uppercase tracking-wider text-blue-400">Image preview</div>}</div><div className="flex-1 p-4"><h3 className="text-lg font-black text-slate-950">{card.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{card.description}</p></div></article>)}</div></section> : null}

      {numbered.length ? <section id={ids.numbered} data-region="numbered-list" className="scroll-mt-28 pt-10"><Heading>{b?.numbered_list.heading || 'Symptoms to watch'}</Heading><ol className="mt-5 space-y-4">{numbered.map((item, index) => <li key={`${item.title}-${index}`} className="flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#1686d9] text-xs font-black text-white">{index + 1}</span><div><h3 className="text-sm font-black text-slate-950">{item.title}</h3><p className="mt-0.5 text-sm leading-5 text-slate-600">{item.description}</p></div></li>)}</ol></section> : null}

      {expert ? <section id={ids.expert} data-region="expert-quote" className="relative mt-10 scroll-mt-28 overflow-hidden rounded-[18px] border border-blue-100 bg-[#eef8ff] p-5 sm:p-6"><Quote size={66} className="absolute right-4 top-2 text-blue-100" aria-hidden="true" /><div className="relative flex flex-col gap-4 sm:flex-row sm:items-center"><div className="relative grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-full border-[3px] border-white bg-blue-100 text-lg font-black text-[#0875c9] shadow-sm">{expert.image ? <Image src={expert.image} alt={expert.alt || expert.name || 'Medical expert'} fill sizes="64px" className="object-cover" unoptimized /> : <span aria-hidden="true">{expert.name.split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join('').toUpperCase() || <MessageSquareQuote />}</span>}</div><div className="min-w-0 flex-1"><p className="text-[15px] italic leading-6 text-slate-800">“{expert.quote}”</p><div className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-[#0875c9]">{expert.name}</p><p className="text-xs font-semibold text-slate-500">{expert.role}</p></div>{expert.profile_url ? <span className="inline-flex w-fit border-b border-[#1686d9] text-xs font-bold text-[#0875c9]" aria-disabled="true">View profile&nbsp; →</span> : null}</div></div></div></section> : null}

      {cta ? <section id={ids.guidance} data-region="medical-cta" className="mt-10 scroll-mt-28 rounded-[18px] bg-[#082c4c] p-5 text-white sm:p-6"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white/10"><CircleAlert size={19} aria-hidden="true" /></span><div className="min-w-0 flex-1"><h2 className="text-lg font-black sm:text-xl">{cta.heading}</h2><p className="mt-2 text-sm leading-6 text-blue-100">{cta.description}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row">{primary ? <button type="button" disabled className="w-full rounded-lg bg-[#1686d9] px-4 py-2.5 text-sm font-black text-white disabled:opacity-80 sm:w-auto">{primary.label}</button> : null}{secondary ? <button type="button" disabled className="w-full rounded-lg border border-white/40 px-4 py-2.5 text-sm font-black text-white disabled:opacity-80 sm:w-auto">{secondary.label}</button> : null}</div></div></div></section> : null}

      {faqs.length ? <section id={ids.faq} data-region="faq" className="scroll-mt-28 pt-10"><Heading>{b?.faq.heading || 'Frequently asked questions'}</Heading><div className="mt-5 grid gap-5 md:grid-cols-2">{props.image || props.showFeaturedImagePlaceholder ? <div className="relative min-h-[280px] overflow-hidden rounded-2xl bg-gradient-to-br from-blue-100 to-cyan-50 md:min-h-[310px]">{props.image ? <Image src={props.image} alt={props.imageAlt || 'Article illustration'} fill loading="lazy" sizes="(min-width:768px) 330px,100vw" className="object-cover" unoptimized /> : <div className="grid h-full min-h-[280px] place-items-center text-xs font-bold uppercase tracking-wider text-blue-400">FAQ image</div>}</div> : null}<div className="space-y-2">{faqs.map((item, index) => { const expanded = openFaq === index; const panel = `template-two-faq-${index}`; return <div key={`${item.question}-${index}`} className="overflow-hidden rounded-xl bg-[#eef8ff]"><button type="button" aria-expanded={expanded} aria-controls={panel} onClick={() => setOpenFaq(expanded ? -1 : index)} className="focus-ring flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left text-sm font-black text-slate-900"><span>{item.question}</span>{expanded ? <ChevronUp size={17} aria-hidden="true" /> : <ChevronDown size={17} aria-hidden="true" />}</button>{expanded ? <div id={panel} role="region" className="border-t border-blue-100 px-4 py-3.5 text-sm leading-6 text-slate-600">{item.answer}</div> : null}</div>; })}</div></div></section> : null}

      {b && (b.feedback.enabled || b.share.enabled) ? <section data-region="engagement" className="mt-11 flex flex-col gap-4 border-y border-slate-200 py-5 sm:flex-row sm:items-center sm:justify-between">{b.feedback.enabled ? <div className="flex flex-wrap items-center gap-2 text-sm font-bold text-slate-700"><span className="mr-1">{b.feedback.prompt || 'Was this helpful?'}</span><button type="button" disabled className="rounded-full border border-blue-200 px-3 py-1.5 text-[#0875c9] disabled:opacity-70">Yes</button><button type="button" disabled className="rounded-full border border-slate-200 px-3 py-1.5 text-slate-600 disabled:opacity-70">No</button></div> : null}{b.share.enabled ? <div className="flex items-center gap-2 text-sm font-bold text-slate-700"><span>Share</span><button type="button" disabled aria-label="Share article" className="grid h-9 w-9 place-items-center rounded-full border border-slate-200 disabled:opacity-70"><Share2 size={15} aria-hidden="true" /></button><button type="button" disabled aria-label="Print article" className="grid h-9 w-9 place-items-center rounded-full border border-slate-200 disabled:opacity-70"><Printer size={15} aria-hidden="true" /></button></div> : null}</section> : null}
      {b?.disclaimer.enabled && b.disclaimer.text.trim() ? <section data-region="medical-disclaimer" className="mt-7 rounded-2xl bg-[#eef8ff] p-4 text-xs italic leading-5 text-slate-700"><div className="flex items-start gap-3"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[#0875c9]" aria-hidden="true" /><p><strong className="font-black not-italic text-slate-800">Medical disclaimer: </strong>{b.disclaimer.text}</p></div></section> : null}
    </main>

    <aside data-region="table-of-contents-sidebar" className="min-w-0">
      <details className="rounded-2xl bg-[#eef8ff] p-5 lg:hidden"><summary className="cursor-pointer text-xs font-black uppercase tracking-[.15em] text-[#0875c9]">In This Article</summary><div className="mt-4"><TableOfContents items={toc} activeId={active} heading="In This Article" hideHeading ariaLabel="Mobile table of contents" /></div></details>
      <div className="mt-5 space-y-5 lg:sticky lg:top-24 lg:mt-0">
        <div className="hidden rounded-2xl bg-[#eef8ff] p-4 lg:block"><TableOfContents items={toc} activeId={active} heading="In This Article" /></div>
        <section aria-label="Appointment options" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_10px_28px_-24px_rgba(8,47,73,.4)]"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-[#0875c9]"><Stethoscope size={19} aria-hidden="true" /></span><h2 className="mt-4 text-lg font-black text-slate-950">Need an eye-care review?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use a configured article action to contact the care team.</p><div className="mt-4 space-y-2">{primary ? <button type="button" disabled className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#1686d9] px-4 py-2.5 text-sm font-black text-white disabled:opacity-80"><CalendarDays size={16} aria-hidden="true" />{primary.label}</button> : null}{secondary ? <button type="button" disabled className="flex w-full items-center justify-center gap-2 rounded-xl border border-blue-200 px-4 py-2.5 text-sm font-black text-[#0875c9] disabled:opacity-80"><Phone size={16} aria-hidden="true" />{secondary.label}</button> : null}{!primary && !secondary ? <p className="rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-500">Contact actions have not been configured.</p> : null}</div></section>
        <section aria-label="Newsletter preview" className="rounded-2xl border border-slate-200 bg-white p-5"><Mail size={20} className="text-[#0875c9]" aria-hidden="true" /><h2 className="mt-3 text-lg font-black text-slate-950">Get eye-care guidance</h2><p className="mt-2 text-sm leading-6 text-slate-600">Newsletter signup is a visual preview and is not connected to a subscription service.</p><div className="mt-4"><label htmlFor="template-two-newsletter" className="sr-only">Email address</label><input id="template-two-newsletter" type="email" disabled placeholder="Email address" className="h-10 w-full rounded-xl border border-slate-200 px-3 text-sm disabled:bg-slate-50" /><button type="button" disabled className="mt-2 w-full rounded-xl bg-[#1686d9] px-4 py-2.5 text-sm font-black text-white disabled:opacity-70">Subscribe</button></div></section>
      </div>
    </aside></div>
  </article>;
}
